[tool.ruff]


ignore = [
    # `from X import *` used; unable to detect undefined names.
    # It's an unfortunate manim convention to use `from manim import *`.
    "F403",
    # X may be undefined, or defined from star imports.
    # Same reason.
    "F405",
    # Ambiguous variable name: `l`
    # This one is kind of pedantic.
    "E741",
]

select = [
    "I", # Sort imports
    "F401", # Remove unused imports
]